version: "3.4"

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080